apiVersion: v1
kind: Pod
metadata:
  name: grade-submission-api
  labels:
    app.kubernetes.io/name: grade-submission
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: grade-submission-api
spec:
  containers:
    - name: grade-submission-api
      image: rslim087/kubernetes-course-grade-submission-api:stateless-v4
      resources:
        limits:
          memory: '128Mi'
          cpu: '128m'
      ports:
        - containerPort: 3000
    - name: grade-submission-api-health-checker
      image: rslim087/kubernetes-course-grade-submission-api-health-checker
      resources:
        limits:
          memory: '128Mi'
          cpu: '128m'
    
